on:
  workflow_dispatch: {}
name: release-please
jobs:
  release-please:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          package-name: release-please-action
